spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/database_taskmanager
    username: ${USER:postgres}
    password: ${PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatMustBe32CharsOrMore}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.baymakov.taskmanager: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true